"""Add color column to employees

Revision ID: 384bea7b0aa8
Revises: 
Create Date: 2024-06-03 19:35:39.473981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384bea7b0aa8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_test')
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.add_column('employees', sa.Column('color', sa.String(), nullable=True))
    op.alter_column('employees', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.alter_column('employees', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('employees', 'color')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.create_table('my_test',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
